version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/auth
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - AUTH_SERVICE_URL=http://auth:3000
      - EVENT_SERVICE_URL=http://event:3002
      - JWT_SECRET=your-secret-key
    depends_on:
      - auth
      - event

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/event
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 